# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ffuenf/ubuntu-12.04.4-server-amd64"
  config.vm.box_url = "https://s3.amazonaws.com/centos-6.5-vbox/ffuenf-VAGRANTSLASH-ubuntu-12.04.4-server-amd64.box"

  config.vm.provision "shell", path: "setup.sh"
  
  config.vm.synced_folder ".", "/test/"
  
  config.vm.provider :virtualbox do |vb|
    
    vb.name = "vagrant-migrates-ubuntu"
    vb.gui = false # Don't boot with headless mode
    vb.customize ["modifyvm", :id, "--memory", "4096"]
    vb.cpus = 2

  end
  
end
